name: Testing

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ *.cpp -o main.exe
      - run: main.exe units/Bela.txt units/Janos.txt